# Generated by Django 3.1.7 on 2021-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=456, max_length=11),
            preserve_default=False,
        ),
    ]
