# Generated by Django 3.1.7 on 2021-03-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
